spring.application.name=TaskFlow

spring.datasource.url=${Database_Host}
spring.datasource.username=${Database_Username}
spring.datasource.password=${Database_Password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret Key
jwt.secret=${JWT_Secret_Key}
jwt.expiration=3600000


